AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - '.pryrc'

Style/Encoding:
  Enabled: false

Documentation:
  Enabled: false
  
Metrics/LineLength:
  Max: 120
